### ISSUE TITLE
Installation error: 'please install setuptools'

### ISSUE THREAD

**Issue by taylanmusluman** [chlubba/PyPNS#1]
Hello, I have trouble with the installation on my Mac (10.14.5) as it says that _setuptools_ is not installed, even though it is. Any ideas about what might be causing the issue?

`Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (40.8.0)`

> Collecting pypns
  Downloading https://files.pythonhosted.org/packages/f8/e1/29e2d66ada5bb765455fcab783b57a4a977de35e7a45db638ec54f521220/PyPNS-0.0.4.tar.gz (44kB)
    100% |████████████████████████████████| 51kB 1.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-hpdrgh6u/pypns/setup.py", line 9
        raise ie, 'please install setuptools'
                ^
    SyntaxError: invalid syntax
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-hpdrgh6u/pypns/

**Comment by lbazan** [comment]
not fixed!
